### ISSUE TITLE
Kafka RecordBatch must contain at least one record

### ISSUE THREAD

**Issue by kordiangrabowski** [trisquareeu/kafkit#50]
According to the [documentation](https://kafka.apache.org/documentation/#messageformat), the Kafka RecordBatch must contain at least one record (either control or standard record):

> The technical term for a batch of messages is a record batch, **and a record batch contains one or more records.**

 This behavior is also reflected in the [Java Kafka Clients](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/record/DefaultRecordBatch.java#L582). 
 
Please fix the `RecordBatch` class to not allow for creating batches with less than 1 record.

**Comment by Kalin8900** [comment]
According to Java Client record batch can contain 0 records

```java
if (numRecords < 0)
                throw new InvalidRecordException("Found invalid record count " + numRecords + " in magic v" +
                        magic() + " batch");
```

Should we also accept that?

**Comment by kordiangrabowski** [comment]
I believe, we should not throw an Error on the deserialization if such empty batch is fetched from the broker, but simultaneously we should not allow for creating such "degenerated" batches on our side.
